### ISSUE TITLE
Icons transitions not happening properly

### ISSUE THREAD

**Issue by simona89** [prscX/react-native-iconic#5]
Hi,

Thank you providing a good library for common icon animations.

I am using basic down and up shapes in my view. But when I click on the down icon, first time it shows proper transition(up icon). But after that it always shows a vertical line and down icon.

Can you please look into the issue.

Thanks in Advance.

**Comment by prscX** [comment]
Thanks @simona89 for raising the issue.

I have pushed a release with the fix, can you please install latest version and verify the same. Please let me know in case you still face the same issue.

Thanks
</ Pranav >
